<?php

declare(strict_types=1);

return [
    'AvLeg_01' => 'LEGAL NOTICE AND GENERAL TERMS OF USE',
    'AvLeg_02' => 'I. GENERAL INFORMATION',
    'AvLeg_03' => 'In compliance with the obligation to provide information in accordance with Law 34/2002 on Information Society Services and Electronic Commerce (LSSI-CE) of 11 July, the following general information on this website is provided below:',
    'AvLeg_04' => 'The ownership of this website, la-cocinita.com, (hereinafter, Website) is held by: José García Ferreis, with NIF: 43795740Z, and whose contact details are:',
    'AvLeg_05' => 'Address',
    'AvLeg_06' => 'Contact telephone',
    'AvLeg_45' => 'Contact email',
    'AvLeg_07' => 'II. GENERAL TERMS AND CONDITIONS OF USE',
    'AvLeg_08' => 'The object of the conditions: The Website',
    'AvLeg_09' => 'The purpose of these General Terms and Conditions of Use (hereinafter referred to as Terms) is to regulate access to and use of the Website. For the purposes of these Terms and Conditions, the Website shall be understood to mean: the external appearance of the screen interfaces, both static and dynamic, i.e. the navigation tree; and all the elements integrated both in the screen interfaces and in the navigation tree (hereinafter, Content) and all those online services or resources offered to Users (hereinafter, Services).',
    
    'AvLeg_10' => 'La Cocinita reserves the right to modify, at any time and without prior notice, the presentation and configuration of the Website and the Contents and Services that may be incorporated therein. The User acknowledges and accepts that at any time La Cocinita may interrupt, deactivate and/or cancel any of these elements that are integrated in the Website or access to them.',
    'AvLeg_11' => 'Access to the Website by the User is free and, as a general rule, is free without the User having to provide a consideration in order to enjoy it, except for the cost of connection through the telecommunications network supplied by the access provider contracted by the User.',
    'AvLeg_12' => 'The use of any of the Contents or Services of the Web Site may be made by means of prior subscription or registration by the User',
    'AvLeg_13' => 'The User',
    'AvLeg_14' => 'The access, browsing and use of the Website confers the condition of User, and therefore the User accepts, from the moment he/she starts browsing the Website, all the Conditions established herein, as well as any subsequent modifications, without prejudice to the application of the corresponding legal regulations of obligatory compliance as the case may be. Given the relevance of the above, the User is recommended to read them every time he/she visits the Website.',
    'AvLeg_15' => 'The La Cocinita Website provides a wide range of information, services and data. The User assumes responsibility for the correct use of the Website. This responsibility extends to:',
    'AvLeg_16' => 'A use of the information, Contents and/or Services and data offered by La Cocinita that is not contrary to the provisions of these Conditions, the Law, morality or public order, or that in any other way could damage the rights of third parties or the functioning of the Website.',
    'AvLeg_17' => 'The veracity and legality of the information provided by the User in the forms provided by La Cocinita for access to certain Contents or Services offered by the Website. In any case, the User shall immediately notify La Cocinita of any event that allows the improper use of the information registered in said forms, such as, but not limited to, theft, loss, or unauthorised access to identifiers and/or passwords, in order to proceed to their immediate cancellation.',
    'AvLeg_18' => 'Mere access to this Website does not imply any type of commercial relationship between La Cocinita and the User',
    'AvLeg_19' => 'The User declares to be of legal age and to have sufficient legal capacity to be bound by these Conditions. Therefore, this La Cocinita Website is not directed at minors. La Cocinita declines any responsibility for failure to comply with this requirement',

    'AvLeg_20' => 'The Website is primarily intended for Users residing in Spain. La Cocinita makes no representation that the Website complies with the laws of other countries, either in whole or in part. If the User resides or is domiciled in another place and decides to access and/or browse the Website, he/she does so at his/her own risk, and must ensure that such access and browsing complies with the applicable local legislation, and La Cocinita accepts no liability whatsoever that may arise from such access',
    'AvLeg_21' => 'III. ACCESS AND NAVIGATION ON THE WEB SITE: EXCLUSION OF GUARANTEES AND LIABILITY',
    'AvLeg_22' => 'La Cocinita does not guarantee the continuity, availability and usefulness of the Website, nor of the Contents or Services. La Cocinita will make every effort to ensure the proper functioning of the Website, however, it makes no representations or warranties that access to this Website will be uninterrupted or error-free',
    'AvLeg_23' => 'Neither does it accept any responsibility or guarantee that the content or software that can be accessed through this Website is free of error or that it will not cause damage to the User\'s computer system (software and hardware). Under no circumstances shall La Cocinita be liable for any loss, damage or harm of any kind arising from accessing, browsing and using the Website, including, but not limited to, those caused to computer systems or those caused by the introduction of viruses.',
    'AvLeg_24' => 'La Cocinita is also not responsible for any damages that may be caused to users by an inappropriate use of this Website. In particular, it shall not be held responsible in any way whatsoever for any telecommunications failures, interruptions, faults or defects that may occur',
    'AvLeg_25' => 'IV. LINKS POLICY',
    'AvLeg_26' => 'We inform you that the La Cocinita Website places or may place at the disposal of Users means of linking (such as, among others, links, banners, buttons), directories and search engines that allow Users to access websites belonging to and/or managed by third parties.',
    'AvLeg_27' => 'The installation of these links, directories and search engines on the Website is intended to facilitate User\'s search for and access to information available on the Internet, without being considered as a suggestion, recommendation or invitation to visit them.',
    'AvLeg_28' => 'La Cocinita does not itself or through third parties offer or market the products and/or services available on such linked sites.',
    'AvLeg_29' => 'Likewise, it does not guarantee the technical availability, accuracy, veracity, validity or legality of sites outside its property that can be accessed through the links',

    'AvLeg_30' => 'La Cocinita will in no case review or control the content of other websites, nor does it approve, examine or make its own the products and services, contents, files and any other material existing in the aforementioned linked sites',
    'AvLeg_31' => 'La Cocinita assumes no responsibility for any damages that may arise from the access, use, quality or legality of the contents, communications, opinions, products and services of the websites not managed by La Cocinita and which are linked to this Website.',
    'AvLeg_32' => 'The User or third party who makes a hyperlink from a web page of another, different, website to the La Cocinita Website must know that:',
    'AvLeg_33' => 'No reproduction - in whole or in part - of any of the Contents and/or Services of the Website is permitted without the express authorisation of La Cocinita',
    'AvLeg_34' => 'No false, inaccurate or incorrect statement about the La Cocinita Website, or the Content and/or Services of the Website is permitted',
    'AvLeg_35' => 'With the exception of the hyperlink, the website in which said hyperlink is established shall not contain any element of this Website protected as intellectual property by Spanish law, unless expressly authorised by La Cocinita.',
    'AvLeg_36' => 'The establishment of the hyperlink shall not imply the existence of a relationship between La Cocinita and the owner of the website from which it is made, nor the knowledge and acceptance by La Cocinita of the contents, services and/or activities offered on said website, and vice versa.',
    'AvLeg_37' => 'V. INTELLECTUAL AND INDUSTRIAL PROPERTY',
    'AvLeg_38' => 'La Cocinita itself or as an assignee, is the owner of all the intellectual and industrial property rights of the Website, as well as of the elements contained therein (including, but not limited to, images, sound, audio, video, software or texts, trademarks or logos, combinations of colours, structure and design, selection of materials used, computer programs necessary for its operation, access and use, etc.). They are, therefore, works protected as intellectual property by the Spanish legal system, being applicable to them both the Spanish and Community regulations in this field, as well as the international treaties relating to the matter and signed by Spain.',
    'AvLeg_39' => 'All rights reserved. By virtue of the provisions of the Intellectual Property Law, the reproduction, distribution and public communication, including the making available modality, of all or part of the contents of this website, for commercial purposes, in any medium and by any technical means, without the authorisation of La Cocinita, are expressly prohibited.',

    'AvLeg_40' => 'The User undertakes to respect the intellectual and industrial property rights of La Cocinita. You may view the elements of the Website or even print them, copy them and store them on the hard drive of your computer or any other physical medium as long as it is exclusively for your personal use. The User, however, may not remove, alter or manipulate any protection device or security system installed on the Website.',
    'AvLeg_41' => 'In the event that the User or third party considers that any of the Contents of the Website involves a violation of the rights of protection of intellectual property, he/she must immediately inform La Cocinita through the contact details in the GENERAL INFORMATION section of this Legal Notice and General Conditions of Use.',
    'AvLeg_42' => 'VI. LEGAL ACTIONS, APPLICABLE LAW AND JURISDICTION',
    'AvLeg_43' => 'La Cocinita reserves the right to bring any civil or criminal action it deems necessary for improper use of the Website and its Contents, or for breach of these Conditions',
    'AvLeg_44' => 'The relationship between the User and La Cocinita will be governed by the regulations in force and applicable in Spanish territory. Should any controversy arise in relation to the interpretation and/or application of these Conditions, the parties will submit their conflicts to the ordinary jurisdiction, submitting themselves to the judges and courts that correspond according to law.',
    
];